
server:
  port: 8080

spring:
  datasource:
    username: zhizhi
    password: zhizhi0828
    url: jdbc:mysql://139.9.200.208:3306/homework?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.xiaozhao.dao


#showSql
logging:
  level:
    com:
      example:
        mapper : debug